- name: 'install the nginx.conf file on to the remote machine'
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  register: nginx_config
- name: 'reload nginx'
  service:
    name: nginx
    state: reloaded
  when: nginx_config.changed