---
- name: Setup manager
  hosts: swarm-managers
  become: yes
  roles:
  - docker_install
  - swarm_manager
- name: Setup workers
  hosts: swarm-workers
  become: yes
  roles:
  - docker_install
  - swarm_worker       
- name: NGINX
  hosts: NGINX
  become: yes
  roles:
  - NGINX            
