CREATE TABLE IF NOT EXISTS character
(
id INTEGER NOT NULL AUTO_INCREMENT,
clss VARCHAR(10) NOT NULL,
race VARCHAR(10) NOT NULL,
stat VARCHAR(10) NOT NULL,
PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;